dump diffs - refactor

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -97,31 +97,30 @@ runs:
         set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
 
         echo "##[group]Starting diff against default branch"
-        default_branch="$DEFAULT_BRANCH"
 
         shopt -s globstar nullglob
         for file in **/dependencies*.log; do
             fname=$(basename "$file")
 
-            match_path=$(git ls-tree -r --name-only "origin/$default_branch" | grep "/$fname$" | head -n1 || true)
-            if [[ -z "$match_path" ]]; then
-                echo "::notice::No matching file for '$fname' in $default_branch"
+            old_dep_log_file=$(git ls-tree -r --name-only "origin/$DEFAULT_BRANCH" | grep "/$fname$" | head -n1 || true)
+            if [[ -z "$old_dep_log_file" ]]; then
+                echo "::notice::No matching file for '$fname' in $DEFAULT_BRANCH"
                 cat "$file"
                 continue
             fi
 
-            echo "====> Diffing $file with $default_branch:$match_path <===="
+            echo "====> Diffing $file with $DEFAULT_BRANCH:$old_dep_log_file <===="
             tmp_ref="/tmp/old_$fname"
-            git show "origin/$default_branch:$match_path" > "$tmp_ref" || {
-                echo "::warning::Failed to extract $match_path from $default_branch"
+            git show "origin/$DEFAULT_BRANCH:$old_dep_log_file" > "$tmp_ref" || {
+                echo "::warning::Failed to extract $old_dep_log_file from $DEFAULT_BRANCH"
                 continue
             }
 
             echo "::group::Diff: $file"
             if ! diff --color=always -u "$tmp_ref" "$file"; then
-                echo "::notice::Diff above for $file vs $default_branch:$match_path"
+                echo "::notice::Diff above for $file vs $DEFAULT_BRANCH:$old_dep_log_file"
             else
-                echo "::notice::$fname is unchanged from $default_branch"
+                echo "::notice::$fname is unchanged from $DEFAULT_BRANCH"
             fi
             echo "::endgroup::"
         done
